### ISSUE TITLE
Reporte - Actividad 6

### ISSUE THREAD

**Issue by irving1989** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-bleachers#1]
[Practica 6 - Fundamentos de desarrollo de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-bleachers/files/13194630/Practica.6.-.Fundamentos.de.desarrollo.de.software.pdf)

**Comment by Julissamigdalia** [comment]
Portada: Excelente 25 Puntos
Procedimiento: Excelente 25 Puntos
Figuras e Ilustraciones y fotografías: Execelente 25 puntos
Resultados y conclusiones: Excelente 25 puntos
Calificación: 20/20

**Comment by Julissamigdalia** [comment]
Portada: Excelente 25 puntos
Procedimiento: Excelente 25 puntos 
Figuras Ilustración y figuras: Excelente 25 puntos
Resultados y conlusiones: Excelente 25 puntos 
Calificación: 30/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
